//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostNL.LocationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetNearestLocationsRequest", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class GetNearestLocationsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Message MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Countrycode {
            get {
                return this.CountrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountrycodeField, value) != true)) {
                    this.CountrycodeField = value;
                    this.RaisePropertyChanged("Countrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Message Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class Location : PostNL.LocationService.BaseLocation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Coordinate CoordinatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNrExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Coordinate Coordinates {
            get {
                return this.CoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesField, value) != true)) {
                    this.CoordinatesField = value;
                    this.RaisePropertyChanged("Coordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HouseNr {
            get {
                return this.HouseNrField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseNrField, value) != true)) {
                    this.HouseNrField = value;
                    this.RaisePropertyChanged("HouseNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HouseNrExt {
            get {
                return this.HouseNrExtField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseNrExtField, value) != true)) {
                    this.HouseNrExtField = value;
                    this.RaisePropertyChanged("HouseNrExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Postalcode {
            get {
                return this.PostalcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalcodeField, value) != true)) {
                    this.PostalcodeField = value;
                    this.RaisePropertyChanged("Postalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageTimeStamp {
            get {
                return this.MessageTimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTimeStampField, value) != true)) {
                    this.MessageTimeStampField = value;
                    this.RaisePropertyChanged("MessageTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseLocation", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PostNL.LocationService.LocationArea))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PostNL.LocationService.Location))]
    public partial class BaseLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllowSundaySortingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DeliveryOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpeningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] OptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AllowSundaySorting {
            get {
                return this.AllowSundaySortingField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowSundaySortingField, value) != true)) {
                    this.AllowSundaySortingField = value;
                    this.RaisePropertyChanged("AllowSundaySorting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryDateField, value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] DeliveryOptions {
            get {
                return this.DeliveryOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryOptionsField, value) != true)) {
                    this.DeliveryOptionsField = value;
                    this.RaisePropertyChanged("DeliveryOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OpeningTime {
            get {
                return this.OpeningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpeningTimeField, value) != true)) {
                    this.OpeningTimeField = value;
                    this.RaisePropertyChanged("OpeningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationArea", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class LocationArea : PostNL.LocationService.BaseLocation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Coordinate CoordinatesNorthWestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Coordinate CoordinatesSouthEastField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Coordinate CoordinatesNorthWest {
            get {
                return this.CoordinatesNorthWestField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesNorthWestField, value) != true)) {
                    this.CoordinatesNorthWestField = value;
                    this.RaisePropertyChanged("CoordinatesNorthWest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Coordinate CoordinatesSouthEast {
            get {
                return this.CoordinatesSouthEastField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesSouthEastField, value) != true)) {
                    this.CoordinatesSouthEastField = value;
                    this.RaisePropertyChanged("CoordinatesSouthEast");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinate", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class Coordinate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationsResponse", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class GetLocationsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.ResponseLocation[] GetLocationsResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Warning[] WarningsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.ResponseLocation[] GetLocationsResult {
            get {
                return this.GetLocationsResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetLocationsResultField, value) != true)) {
                    this.GetLocationsResultField = value;
                    this.RaisePropertyChanged("GetLocationsResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Warning[] Warnings {
            get {
                return this.WarningsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningsField, value) != true)) {
                    this.WarningsField = value;
                    this.RaisePropertyChanged("Warnings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseLocation", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class ResponseLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DeliveryOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.OpeningHours OpeningHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.PartnerLocationCode[] PartnerLocationCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetailFormulaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetailNetworkIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaleschannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] DeliveryOptions {
            get {
                return this.DeliveryOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryOptionsField, value) != true)) {
                    this.DeliveryOptionsField = value;
                    this.RaisePropertyChanged("DeliveryOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.OpeningHours OpeningHours {
            get {
                return this.OpeningHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.OpeningHoursField, value) != true)) {
                    this.OpeningHoursField = value;
                    this.RaisePropertyChanged("OpeningHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.PartnerLocationCode[] PartnerLocationCodes {
            get {
                return this.PartnerLocationCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerLocationCodesField, value) != true)) {
                    this.PartnerLocationCodesField = value;
                    this.RaisePropertyChanged("PartnerLocationCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartnerName {
            get {
                return this.PartnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerNameField, value) != true)) {
                    this.PartnerNameField = value;
                    this.RaisePropertyChanged("PartnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RetailFormulaName {
            get {
                return this.RetailFormulaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailFormulaNameField, value) != true)) {
                    this.RetailFormulaNameField = value;
                    this.RaisePropertyChanged("RetailFormulaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RetailNetworkID {
            get {
                return this.RetailNetworkIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailNetworkIDField, value) != true)) {
                    this.RetailNetworkIDField = value;
                    this.RaisePropertyChanged("RetailNetworkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Saleschannel {
            get {
                return this.SaleschannelField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleschannelField, value) != true)) {
                    this.SaleschannelField = value;
                    this.RaisePropertyChanged("Saleschannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TerminalType {
            get {
                return this.TerminalTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalTypeField, value) != true)) {
                    this.TerminalTypeField = value;
                    this.RaisePropertyChanged("TerminalType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Warning", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class Warning : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoorcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNrExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Buildingname {
            get {
                return this.BuildingnameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingnameField, value) != true)) {
                    this.BuildingnameField = value;
                    this.RaisePropertyChanged("Buildingname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Countrycode {
            get {
                return this.CountrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountrycodeField, value) != true)) {
                    this.CountrycodeField = value;
                    this.RaisePropertyChanged("Countrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Doorcode {
            get {
                return this.DoorcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DoorcodeField, value) != true)) {
                    this.DoorcodeField = value;
                    this.RaisePropertyChanged("Doorcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HouseNr {
            get {
                return this.HouseNrField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseNrField, value) != true)) {
                    this.HouseNrField = value;
                    this.RaisePropertyChanged("HouseNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HouseNrExt {
            get {
                return this.HouseNrExtField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseNrExtField, value) != true)) {
                    this.HouseNrExtField = value;
                    this.RaisePropertyChanged("HouseNrExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpeningHours", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class OpeningHours : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FridayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MondayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SaturdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SundayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ThursdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TuesdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WednesdayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Friday {
            get {
                return this.FridayField;
            }
            set {
                if ((object.ReferenceEquals(this.FridayField, value) != true)) {
                    this.FridayField = value;
                    this.RaisePropertyChanged("Friday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Monday {
            get {
                return this.MondayField;
            }
            set {
                if ((object.ReferenceEquals(this.MondayField, value) != true)) {
                    this.MondayField = value;
                    this.RaisePropertyChanged("Monday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Saturday {
            get {
                return this.SaturdayField;
            }
            set {
                if ((object.ReferenceEquals(this.SaturdayField, value) != true)) {
                    this.SaturdayField = value;
                    this.RaisePropertyChanged("Saturday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Sunday {
            get {
                return this.SundayField;
            }
            set {
                if ((object.ReferenceEquals(this.SundayField, value) != true)) {
                    this.SundayField = value;
                    this.RaisePropertyChanged("Sunday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Thursday {
            get {
                return this.ThursdayField;
            }
            set {
                if ((object.ReferenceEquals(this.ThursdayField, value) != true)) {
                    this.ThursdayField = value;
                    this.RaisePropertyChanged("Thursday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Tuesday {
            get {
                return this.TuesdayField;
            }
            set {
                if ((object.ReferenceEquals(this.TuesdayField, value) != true)) {
                    this.TuesdayField = value;
                    this.RaisePropertyChanged("Tuesday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Wednesday {
            get {
                return this.WednesdayField;
            }
            set {
                if ((object.ReferenceEquals(this.WednesdayField, value) != true)) {
                    this.WednesdayField = value;
                    this.RaisePropertyChanged("Wednesday");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartnerLocationCode", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class PartnerLocationCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CifException", Namespace="http://postnl.nl/cif/services/common/")]
    [System.SerializableAttribute()]
    public partial class CifException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.ExceptionData[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PostNL.LocationService.ExceptionData[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionData", Namespace="http://postnl.nl/cif/services/common/")]
    [System.SerializableAttribute()]
    public partial class ExceptionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorNumberField, value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationsInAreaRequest", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class GetLocationsInAreaRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.LocationArea LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Message MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Countrycode {
            get {
                return this.CountrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountrycodeField, value) != true)) {
                    this.CountrycodeField = value;
                    this.RaisePropertyChanged("Countrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.LocationArea Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Message Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationRequest", Namespace="http://postnl.nl/cif/domain/LocationWebService/")]
    [System.SerializableAttribute()]
    public partial class GetLocationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PostNL.LocationService.Message MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetailNetworkIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PostNL.LocationService.Message Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RetailNetworkID {
            get {
                return this.RetailNetworkIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailNetworkIDField, value) != true)) {
                    this.RetailNetworkIDField = value;
                    this.RaisePropertyChanged("RetailNetworkID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", ConfigurationName="LocationService.ILocationWebService")]
    public interface ILocationWebService {
        
        // CODEGEN: Generating message contract since the operation GetNearestLocations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetNearestLo" +
            "cations", ReplyAction="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetNearestLo" +
            "cationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PostNL.LocationService.CifException), Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetNearestLo" +
            "cationsCifExceptionFault", Name="CifException", Namespace="http://postnl.nl/cif/services/common/")]
        PostNL.LocationService.GetNearestLocationsResponseContract GetNearestLocations(PostNL.LocationService.GetNearestLocationsRequestContract request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetNearestLo" +
            "cations", ReplyAction="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetNearestLo" +
            "cationsResponse")]
        System.Threading.Tasks.Task<PostNL.LocationService.GetNearestLocationsResponseContract> GetNearestLocationsAsync(PostNL.LocationService.GetNearestLocationsRequestContract request);
        
        // CODEGEN: Generating message contract since the operation GetLocationsInArea is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocations" +
            "InArea", ReplyAction="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocations" +
            "InAreaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PostNL.LocationService.CifException), Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocations" +
            "InAreaCifExceptionFault", Name="CifException", Namespace="http://postnl.nl/cif/services/common/")]
        PostNL.LocationService.GetLocationsInAreaResponseContract GetLocationsInArea(PostNL.LocationService.GetLocationsInAreaRequestContract request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocations" +
            "InArea", ReplyAction="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocations" +
            "InAreaResponse")]
        System.Threading.Tasks.Task<PostNL.LocationService.GetLocationsInAreaResponseContract> GetLocationsInAreaAsync(PostNL.LocationService.GetLocationsInAreaRequestContract request);
        
        // CODEGEN: Generating message contract since the operation GetLocation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocation", ReplyAction="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocationR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PostNL.LocationService.CifException), Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocationC" +
            "ifExceptionFault", Name="CifException", Namespace="http://postnl.nl/cif/services/common/")]
        PostNL.LocationService.GetLocationResponseContract GetLocation(PostNL.LocationService.GetLocationRequestContract request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocation", ReplyAction="http://postnl.nl/cif/services/LocationWebService/ILocationWebService/GetLocationR" +
            "esponse")]
        System.Threading.Tasks.Task<PostNL.LocationService.GetLocationResponseContract> GetLocationAsync(PostNL.LocationService.GetLocationRequestContract request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNearestLocationsRequestContract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", Order=0)]
        public PostNL.LocationService.GetNearestLocationsRequest GetNearestLocations;
        
        public GetNearestLocationsRequestContract() {
        }
        
        public GetNearestLocationsRequestContract(PostNL.LocationService.GetNearestLocationsRequest GetNearestLocations) {
            this.GetNearestLocations = GetNearestLocations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNearestLocationsResponseContract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", Order=0)]
        public PostNL.LocationService.GetLocationsResponse GetNearestLocationsResponse;
        
        public GetNearestLocationsResponseContract() {
        }
        
        public GetNearestLocationsResponseContract(PostNL.LocationService.GetLocationsResponse GetNearestLocationsResponse) {
            this.GetNearestLocationsResponse = GetNearestLocationsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationsInAreaRequestContract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", Order=0)]
        public PostNL.LocationService.GetLocationsInAreaRequest GetLocationsInArea;
        
        public GetLocationsInAreaRequestContract() {
        }
        
        public GetLocationsInAreaRequestContract(PostNL.LocationService.GetLocationsInAreaRequest GetLocationsInArea) {
            this.GetLocationsInArea = GetLocationsInArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationsInAreaResponseContract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", Order=0)]
        public PostNL.LocationService.GetLocationsResponse GetLocationsInAreaResponse;
        
        public GetLocationsInAreaResponseContract() {
        }
        
        public GetLocationsInAreaResponseContract(PostNL.LocationService.GetLocationsResponse GetLocationsInAreaResponse) {
            this.GetLocationsInAreaResponse = GetLocationsInAreaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationRequestContract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", Order=0)]
        public PostNL.LocationService.GetLocationRequest GetLocation;
        
        public GetLocationRequestContract() {
        }
        
        public GetLocationRequestContract(PostNL.LocationService.GetLocationRequest GetLocation) {
            this.GetLocation = GetLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocationResponseContract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://postnl.nl/cif/services/LocationWebService/", Order=0)]
        public PostNL.LocationService.GetLocationsResponse GetLocationResponse;
        
        public GetLocationResponseContract() {
        }
        
        public GetLocationResponseContract(PostNL.LocationService.GetLocationsResponse GetLocationResponse) {
            this.GetLocationResponse = GetLocationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationWebServiceChannel : PostNL.LocationService.ILocationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationWebServiceClient : System.ServiceModel.ClientBase<PostNL.LocationService.ILocationWebService>, PostNL.LocationService.ILocationWebService {
        
        public LocationWebServiceClient() {
        }
        
        public LocationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PostNL.LocationService.GetNearestLocationsResponseContract PostNL.LocationService.ILocationWebService.GetNearestLocations(PostNL.LocationService.GetNearestLocationsRequestContract request) {
            return base.Channel.GetNearestLocations(request);
        }
        
        public PostNL.LocationService.GetLocationsResponse GetNearestLocations(PostNL.LocationService.GetNearestLocationsRequest GetNearestLocations1) {
            PostNL.LocationService.GetNearestLocationsRequestContract inValue = new PostNL.LocationService.GetNearestLocationsRequestContract();
            inValue.GetNearestLocations = GetNearestLocations1;
            PostNL.LocationService.GetNearestLocationsResponseContract retVal = ((PostNL.LocationService.ILocationWebService)(this)).GetNearestLocations(inValue);
            return retVal.GetNearestLocationsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostNL.LocationService.GetNearestLocationsResponseContract> PostNL.LocationService.ILocationWebService.GetNearestLocationsAsync(PostNL.LocationService.GetNearestLocationsRequestContract request) {
            return base.Channel.GetNearestLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostNL.LocationService.GetNearestLocationsResponseContract> GetNearestLocationsAsync(PostNL.LocationService.GetNearestLocationsRequest GetNearestLocations) {
            PostNL.LocationService.GetNearestLocationsRequestContract inValue = new PostNL.LocationService.GetNearestLocationsRequestContract();
            inValue.GetNearestLocations = GetNearestLocations;
            return ((PostNL.LocationService.ILocationWebService)(this)).GetNearestLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PostNL.LocationService.GetLocationsInAreaResponseContract PostNL.LocationService.ILocationWebService.GetLocationsInArea(PostNL.LocationService.GetLocationsInAreaRequestContract request) {
            return base.Channel.GetLocationsInArea(request);
        }
        
        public PostNL.LocationService.GetLocationsResponse GetLocationsInArea(PostNL.LocationService.GetLocationsInAreaRequest GetLocationsInArea1) {
            PostNL.LocationService.GetLocationsInAreaRequestContract inValue = new PostNL.LocationService.GetLocationsInAreaRequestContract();
            inValue.GetLocationsInArea = GetLocationsInArea1;
            PostNL.LocationService.GetLocationsInAreaResponseContract retVal = ((PostNL.LocationService.ILocationWebService)(this)).GetLocationsInArea(inValue);
            return retVal.GetLocationsInAreaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostNL.LocationService.GetLocationsInAreaResponseContract> PostNL.LocationService.ILocationWebService.GetLocationsInAreaAsync(PostNL.LocationService.GetLocationsInAreaRequestContract request) {
            return base.Channel.GetLocationsInAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostNL.LocationService.GetLocationsInAreaResponseContract> GetLocationsInAreaAsync(PostNL.LocationService.GetLocationsInAreaRequest GetLocationsInArea) {
            PostNL.LocationService.GetLocationsInAreaRequestContract inValue = new PostNL.LocationService.GetLocationsInAreaRequestContract();
            inValue.GetLocationsInArea = GetLocationsInArea;
            return ((PostNL.LocationService.ILocationWebService)(this)).GetLocationsInAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PostNL.LocationService.GetLocationResponseContract PostNL.LocationService.ILocationWebService.GetLocation(PostNL.LocationService.GetLocationRequestContract request) {
            return base.Channel.GetLocation(request);
        }
        
        public PostNL.LocationService.GetLocationsResponse GetLocation(PostNL.LocationService.GetLocationRequest GetLocation1) {
            PostNL.LocationService.GetLocationRequestContract inValue = new PostNL.LocationService.GetLocationRequestContract();
            inValue.GetLocation = GetLocation1;
            PostNL.LocationService.GetLocationResponseContract retVal = ((PostNL.LocationService.ILocationWebService)(this)).GetLocation(inValue);
            return retVal.GetLocationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostNL.LocationService.GetLocationResponseContract> PostNL.LocationService.ILocationWebService.GetLocationAsync(PostNL.LocationService.GetLocationRequestContract request) {
            return base.Channel.GetLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostNL.LocationService.GetLocationResponseContract> GetLocationAsync(PostNL.LocationService.GetLocationRequest GetLocation) {
            PostNL.LocationService.GetLocationRequestContract inValue = new PostNL.LocationService.GetLocationRequestContract();
            inValue.GetLocation = GetLocation;
            return ((PostNL.LocationService.ILocationWebService)(this)).GetLocationAsync(inValue);
        }
    }
}
